### ISSUE TITLE
openjdk version "11.0.20" 버전에서,  java.io.IOException: HTTP/1.1 header parser received no bytes 에러가 발생합니다.

### ISSUE THREAD

**Issue by fluidhyun** [jenkinsci/dogu-integration-plugin#2]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+8-post-Ubuntu-1ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20+8-post-Ubuntu-1ubuntu122.04, mixed mode, sharing)

Jenkins 2.401.3

### Reproduction steps

1. https://docs.dogutech.io/integration/cicd/jenkins 문서를 참고하여, jenkins 에서 Run dogu routine 을 설정 (self-hosted)
2. Run jenkins job
3. console 에서 에러 확인

### Expected Results

Exception 이 발생하지 않고 Run-Dogu-Routine이 동작

### Actual Results

첨부 에러가 발생하며 실행 실패

API URL: http://192.168.1.226:4000/
Error: HTTP/1.1 header parser received no bytes
java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:565)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
	at io.jenkins.plugins.dogu.api.ApiClient.runRoutine(ApiClient.java:45)
	at io.jenkins.plugins.dogu.DoguRoutineBuilder.perform(DoguRoutineBuilder.java:98)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:164)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
	at hudson.model.Run.execute(Run.java:1900)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:327)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:673)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:297)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:263)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException: EOF reached while reading
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:591)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:632)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:833)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)
Build step 'Run Dogu Routine' marked build as failure
Finished: FAILURE

### Anything else?

openjdk 11 환경에서 HttpClient 를 사용하여 같은 http://192.168.1.226.4000 을 접근했을 때 같은 에러가 발생하였고,
`.version(HttpClient.Version.HTTP_1_1)`
와 같이 http 버전을 명시했을 때에는, 에러가 발생하지 않았습니다.

Execute shell 에 아래 스크립트를 넣어 테스트 했고, curl 시에는 에러가 발생하지 않았습니다.

```
#!/bin/bash
echo "DOGU_API_URL:${DOGU_API_URL}"
curl "http://192.168.1.226:4000"
java -version
javac -version

cat > HttpRequestSample.java <<EOL
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;

public class HttpRequestSample {

    public static void main(String[] args) {
        try {
            // HttpClient 생성
            HttpClient client = HttpClient.newHttpClient();

            // HTTP GET 요청을 위한 HttpRequest 생성
            HttpRequest request = HttpRequest.newBuilder()
                     .version(HttpClient.Version.HTTP_1_1) // 이 부분이 빠지면 같은 에러 발생
                    .uri(new URI("http://192.168.1.226:4000"))
                    .GET()
                    .build();

            // 요청 전송 및 응답 수신
            HttpResponse<String> response = client.send(request, BodyHandlers.ofString());

            // 응답 결과 출력
            System.out.println(response.statusCode());
            System.out.println(response.body());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
EOL
javac HttpRequestSample.java
java HttpRequestSample

```

실행 결과

```
+ echo DOGU_API_URL:http://192.168.1.226:4000/
DOGU_API_URL:http://192.168.1.226:4000/
+ curl http://192.168.1.226:4000/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16  100    16    0     0  16000      0 --:--:-- --:--:-- --:--:-- 16000
Welcome to Dogu!+ java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)
+ javac -version
javac 11.0.19
+ cat
+ javac HttpRequestSample.java
+ java HttpRequestSample
200
Welcome to Dogu!
API URL: http://192.168.1.226:4000/
Error: HTTP/1.1 header parser received no bytes
java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:565)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
	at io.jenkins.plugins.dogu.api.ApiClient.runRoutine(ApiClient.java:45)
	at io.jenkins.plugins.dogu.DoguRoutineBuilder.perform(DoguRoutineBuilder.java:98)
//... 이하 생략
```

**Comment by lumyjuwon** [comment]
@fluidhyun 
Thanks for issuing. This issue is solved in #3

**Comment by lumyjuwon** [comment]
You can use solved plugin by updating dogu-integration-plugin to **27.vd4da_5fea_e29f** version.

**Comment by fluidhyun** [comment]
I have confirmed that this issue is no longer reproducible in version 27.vd4da_5fea_e29f. Thank you.
